# ARC training config

defaults:
  - arch: hrm_v1
  - _self_

hydra:
  output_subdir: null

# Data path
data_path: data\tsp_data

# Hyperparams - Training
global_batch_size: 256

epochs: 2000
eval_interval: 200
checkpoint_every_eval: True

lr: 1e-4
lr_min_ratio: 1.0
lr_warmup_steps: 200

# Standard hyperparameter settings for LM, as used in Llama
beta1: 0.9
beta2: 0.95
weight_decay: 1
puzzle_emb_weight_decay: 1

# Hyperparams - Puzzle embeddings training
puzzle_emb_lr: 1e-2
